# 基础镜像
FROM  openjdk:11-jre

# 维护者信息更新（MAINTAINER 已弃用）
LABEL maintainer="qjyy"

# 创建并设置工作目录
WORKDIR /home/qjyy

# 复制 jar 文件到工作目录
COPY ../../../../target/asp-base-service.jar /home/qjyy/asp-base-service.jar

# 设置时区为中国北京时间
ENV TZ=Asia/Shanghai

# 设置环境变量，如果在运行容器时未指定，将使用这些默认值
ENV NACOS_SERVER_ADDR=localhost:8848
ENV NACOS_NAMESPACE=default
ENV SPRING_PROFILES_ACTIVE=dev

# 启动应用
ENTRYPOINT ["java", "-jar", "asp-base-service.jar"]
